// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfanityService.Application.Db;

#nullable disable

namespace ProfanityService.Application.Db.Migrations
{
    [DbContext(typeof(ProfanityDbContext))]
    [Migration("20250928072921_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProfanityService.Domain.Entity.Profanity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profanities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Word = "fuck"
                        },
                        new
                        {
                            Id = 2,
                            Word = "retard"
                        },
                        new
                        {
                            Id = 3,
                            Word = "docker"
                        },
                        new
                        {
                            Id = 4,
                            Word = "monolith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
