name: HappyHeadlinesDevOps

on:
    push:
        branches:
         - main

permissions:
    contents: read
    packages: write

jobs:
    integration:
        runs-on: ubuntu-latest

        steps:
         - name: Checkout Code
           uses: actions/checkout@v4

         - name: Github Container Registry Sign in
           uses: docker/login-action@v3
           with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

         - name: Build Services
           run: |
            echo "Building services with version number"
            version=v${{ github.run_number }}
            docker compose build article-service comment-service profanity-service draft-service publisher-service newsletter-service

            docker tag ghcr.io/adnanomerbasic/article-service:latest ghcr.io/adnanomerbasic/article-service:$version
            docker tag ghcr.io/adnanomerbasic/comment-service:latest ghcr.io/adnanomerbasic/comment-service:$version
            docker tag ghcr.io/adnanomerbasic/profanity-service:latest ghcr.io/adnanomerbasic/profanity-service:$version
            docker tag ghcr.io/adnanomerbasic/draft-service:latest ghcr.io/adnanomerbasic/draft-service:$version
            docker tag ghcr.io/adnanomerbasic/publisher-service:latest ghcr.io/adnanomerbasic/publisher-service:$version
            docker tag ghcr.io/adnanomerbasic/newsletter-service:latest ghcr.io/adnanomerbasic/newsletter-service:$version

         - name: Deliver Services
           run: |
            echo "Delivering services with version number"
            version=v${{ github.run_number }}
            docker compose push article-service comment-service profanity-service draft-service publisher-service newsletter-service

            docker push ghcr.io/adnanomerbasic/article-service:$version
            docker push ghcr.io/adnanomerbasic/comment-service:$version
            docker push ghcr.io/adnanomerbasic/profanity-service:$version
            docker push ghcr.io/adnanomerbasic/draft-service:$version
            docker push ghcr.io/adnanomerbasic/publisher-service:$version
            docker push ghcr.io/adnanomerbasic/newsletter-service:$version